export enum Functions {
    embedpano = '/documation/embedding#embedpano',
    xml = '/documentation/embedding?id=xml',
    target = '/documentation/embedding?id=target',
    bgcolor = '/documentation/embedding?id=bgcolor',
    vars = '/documentation/embedding?id=vars',
    initvars = '/documentation/embedding?id=initvars',
    basepath = '/documentation/embedding?id=basepath',
    consolelog = '/documentation/embedding?id=consolelog',
    mwheel = '/documentation/embedding?id=mwheel',
    capturetouch = '/documentation/embedding?id=capturetouch',
    focus = '/documentation/embedding?id=focus',
    webgl = '/documentation/embedding?id=webgl',
    webglsettings = '/documentation/embedding?id=webglsettings',
    webxr = '/documentation/embedding?id=webxr',
    mobilescale = '/documentation/embedding?id=mobilescale',
    safearea = '/documentation/embedding?id=safearea',
    touchdevicemousesupport = '/documentation/embedding?id=touchdevicemousesupport',
    fakedevice = '/documentation/embedding?id=fakedevice',
    onready = '/documentation/embedding?id=onready',
    onerror = '/documentation/embedding?id=onerror',
    passQueryParameters = '/documentation/embedding?id=passQueryParameters',
    removepano = '/documentation/embedding?id=removepano',
    krpanoUnload = '/documentation/embedding?id=krpanoUnload',
}